<?php
/**
 * Registry Theme Functions
 *
 * @package Registry
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Theme setup
 */
function registry_theme_setup()
{
    // Add theme support for various features
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('html5', array(
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
        'style',
        'script',
    ));
    
    // Add support for editor styles
    add_theme_support('editor-styles');
    
    // Add support for responsive embeds
    add_theme_support('responsive-embeds');
    
    // Add support for custom logo
    add_theme_support('custom-logo');
    
    // Add support for wide and full alignment
    add_theme_support('align-wide');
    
    // Add support for editor color palette (can be customized per project)
    add_theme_support('editor-color-palette', array());
    
    // Add support for custom font sizes (can be customized per project)
    add_theme_support('editor-font-sizes', array());
}
add_action('after_setup_theme', 'registry_theme_setup');

/**
 * Enqueue scripts and styles
 */
function registry_enqueue_assets()
{
    // Get the theme version
    $theme_version = wp_get_theme()->get('Version');
    
    // Enqueue compiled CSS (generated by @wordpress/scripts)
    wp_enqueue_style(
        'registry-style',
        get_theme_file_uri('build/style-index.css'),
        array(),
        $theme_version
    );
    
    // Enqueue compiled JavaScript (generated by @wordpress/scripts)
    wp_enqueue_script(
        'registry-script',
        get_theme_file_uri('build/index.js'),
        array(),
        $theme_version,
        true
    );
}
add_action('wp_enqueue_scripts', 'registry_enqueue_assets');

/**
 * Register ACF blocks
 */
function registry_register_acf_blocks()
{
    // Check if ACF is active
    if (!function_exists('acf_register_block_type')) {
        return;
    }
    
    // Include blocks registration
    if (file_exists(get_theme_file_path('inc/blocks.php'))) {
        require_once get_theme_file_path('inc/blocks.php');
    }
}
add_action('acf/init', 'registry_register_acf_blocks');

/**
 * Add editor styles
 */
function registry_add_editor_styles()
{
    // Add compiled CSS to the editor
    if (file_exists(get_theme_file_path('build/style-index.css'))) {
        add_editor_style('build/style-index.css');
    }
}
add_action('admin_init', 'registry_add_editor_styles');

/**
 * Customize excerpt length
 */
function registry_excerpt_length($length)
{
    return 20;
}
add_filter('excerpt_length', 'registry_excerpt_length');

/**
 * Customize excerpt more text
 */
function registry_excerpt_more($more)
{
    return '...';
}
add_filter('excerpt_more', 'registry_excerpt_more');