<?php
/**
 * Boilerplate Theme Functions
 *
 * @package Boilerplate
 */

namespace Boilerplate;

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Main Theme Class
 *
 * @since 1.0.0
 */
final class Theme
{
    /**
     * Theme instance
     *
     * @var Theme
     */
    private static $instance = null;

    /**
     * Theme version
     *
     * @var string
     */
    private $version;

    /**
     * Theme text domain
     *
     * @var string
     */
    private $text_domain = 'boilerplate';

    /**
     * Get theme instance
     *
     * @return Theme
     */
    public static function get_instance()
    {
        if (null === self::$instance) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Constructor
     */
    private function __construct()
    {
        $this->version = wp_get_theme()->get('Version');
        $this->init_hooks();
    }

    /**
     * Initialize hooks
     */
    private function init_hooks()
    {
        // Core theme setup
        add_action('after_setup_theme', [$this, 'theme_setup']);
        
        // Assets
        add_action('wp_enqueue_scripts', [$this, 'enqueue_assets']);
        add_action('admin_init', [$this, 'add_editor_styles']);
        
        // ACF
        add_action('acf/init', [$this, 'register_acf_blocks']);
        add_filter('acf/settings/save_json', [$this, 'acf_json_save_point']);
        add_filter('acf/settings/load_json', [$this, 'acf_json_load_point']);
        
        // Content filters
        add_filter('excerpt_length', [$this, 'excerpt_length']);
        add_filter('excerpt_more', [$this, 'excerpt_more']);
    }

    /**
     * Theme setup
     */
    public function theme_setup()
    {
        // Add theme support for various features
        add_theme_support('title-tag');
        add_theme_support('post-thumbnails');
        add_theme_support('html5', [
            'search-form',
            'comment-form',
            'comment-list',
            'gallery',
            'caption',
            'style',
            'script',
        ]);
        
        // Add support for editor styles
        add_theme_support('editor-styles');
        
        // Add support for responsive embeds
        add_theme_support('responsive-embeds');
        
        // Add support for custom logo
        add_theme_support('custom-logo');
        
        // Add support for wide and full alignment
        add_theme_support('align-wide');
        
        // Add support for editor color palette (can be customized per project)
        add_theme_support('editor-color-palette', []);
        
        // Add support for custom font sizes (can be customized per project)
        add_theme_support('editor-font-sizes', []);
        
        // Load theme text domain
        load_theme_textdomain($this->text_domain, get_template_directory() . '/languages');
    }

    /**
     * Enqueue scripts and styles
     */
    public function enqueue_assets()
    {
        // Enqueue compiled CSS (generated by @wordpress/scripts)
        wp_enqueue_style(
            'boilerplate-style',
            get_theme_file_uri('build/index.css'),
            [],
            $this->version
        );
        
        // Enqueue compiled JavaScript (generated by @wordpress/scripts)
        wp_enqueue_script(
            'boilerplate-script',
            get_theme_file_uri('build/index.js'),
            [],
            $this->version,
            true
        );
        
        // Add localized data if needed
        wp_localize_script('boilerplate-script', 'boilerplateData', [
            'ajaxUrl' => admin_url('admin-ajax.php'),
            'nonce' => wp_create_nonce('boilerplate-nonce'),
        ]);
    }

    /**
     * Register ACF blocks
     */
    public function register_acf_blocks()
    {
        // Check if ACF is active
        if (!function_exists('acf_register_block_type')) {
            return;
        }
        
        // Include blocks registration
        if (file_exists(get_theme_file_path('inc/blocks.php'))) {
            require_once get_theme_file_path('inc/blocks.php');
        }
    }

    /**
     * Set ACF JSON save point
     *
     * @param string $path
     * @return string
     */
    public function acf_json_save_point($path)
    {
        // Update path to theme's acf/json folder
        $path = get_stylesheet_directory() . '/acf/json';
        
        return $path;
    }

    /**
     * Add ACF JSON load points
     *
     * @param array $paths
     * @return array
     */
    public function acf_json_load_point($paths)
    {
        // Remove original path (optional)
        unset($paths[0]);
        
        // Add theme's acf/json folder
        $paths[] = get_stylesheet_directory() . '/acf/json';
        
        // Add parent theme's acf/json folder if using child theme
        if (is_child_theme()) {
            $paths[] = get_template_directory() . '/acf/json';
        }
        
        return $paths;
    }

    /**
     * Add editor styles
     */
    public function add_editor_styles()
    {
        // Add compiled CSS to the editor
        if (file_exists(get_theme_file_path('build/index.css'))) {
            add_editor_style('build/index.css');
        }
    }

    /**
     * Customize excerpt length
     *
     * @param int $length
     * @return int
     */
    public function excerpt_length($length)
    {
        return 20;
    }

    /**
     * Customize excerpt more text
     *
     * @param string $more
     * @return string
     */
    public function excerpt_more($more)
    {
        return '...';
    }

    /**
     * Get theme version
     *
     * @return string
     */
    public function get_version()
    {
        return $this->version;
    }

    /**
     * Get text domain
     *
     * @return string
     */
    public function get_text_domain()
    {
        return $this->text_domain;
    }
}

/**
 * Initialize theme
 *
 * @return Theme
 */
function boilerplate()
{
    return Theme::get_instance();
}

// Initialize the theme
boilerplate();